name: Sync liferay-portal fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" 

jobs:
  sync_liferay_portal:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync liferay-page-management/liferay-portal --source liferay/liferay-portal --branch master
        env:
          GH_TOKEN: ${{ secrets.SYNC }}
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
